FROM nginx:latest

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/hackerswork.com.conf /etc/nginx/sites-enabled/hackerswork.com.conf
COPY nginx/server.key /etc/ssl/private/server.key
COPY nginx/server.crt /etc/ssl/certs/server.crt
COPY web /var/www/hackerswork.com/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
